INV_PLAYERLIST	         = _this select 0; 
INV_PLAYERSTRINGLIST    = _this select 1;
INV_CANDOILLEGAL        = _this select 2;
INV_ROLESTRING          = format["%1", player]; 
INV_CALL_CREATVEHICLE   = "core\global\vehdespawn.sqf";
INV_MAX_ITEMS           = 999999;
INV_MAX_DROPS	 	      = 300;
INV_PLAYERCOUNT         = count INV_PLAYERSTRINGLIST;
INV_SaveVclArray        = true; 
INV_VehicleArray        = [];
INV_ServerVclArray      = [];   
INV_SaveObjArray        = false;
INV_shortcuts           = true;
INV_SperrenVerbotArray  = []; //TODO: Missing mission.sqm [copbase1, 250],[sperrenverbot3, 30 ]];
INV_JIP = true; publicVariable "INV_JIP";

_handler = [] execVM "core\functions\INVfunctions.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\functions\createfunctions.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\variables\carparks.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\variables\masterarray.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\variables\shops.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\global\Optimize.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\variables\facharvest.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\variables\licensearray.sqf";
waitUntil {scriptDone _handler};
_handler = [] execVM "core\global\vclarrsave.sqf";