INV_Lizenzen = [
   ["mayorlic",dmv,"Governors license",1000],
   ["boat",dmv,localize "STRS_license_boat",3000],
   ["fboat",dmv,"Ferry Captain License",2500],
   ["esul",atm5,"Fire Rescue Training",100],
   ["bus_license",truckshop,"Bus License",5000],
   ["truck",truckshop,localize "STRS_license_truck",10000],
   ["taxi",taxishop,"Taxi License",5000],
   ["car",dmv,localize "STRS_license_car",1000],
   ["oil",Oil_1,"Oil processor's license",30000],
   ["Baker",Bakery,"Baker's license",10000],
   ["cocaine ga1",gangarea1,"GA1 cocaine Drug processor's license",35000],
   ["lsd ga1",gangarea1,"GA1 LSD Drug processor's license",35000],
   ["heroin ga2",gangarea2,"GA2 Heroin Drug processor's license",35000],
   ["lsd ga2",gangarea2,"GA2 LSD Drug processor's license",35000],
   ["heroin ga3",gangarea3,"GA3 Heroin Drug processor's license",35000],
   ["marijuana ga3",gangarea3,"GA3 Marijuana Drug processor's license",5000],
   ["heroin ga4",gangarea4,"GA4 Heroin Drug processor's license",35000],
   ["marijuana ga4",gangarea4,"GA4 Marijuana Drug processor's license",5000],
   ["air",airshop,localize "STRS_license_air",100000],
   ["air",airshop2,localize "STRS_license_air",100000],
   ["comair",airshop3,"Commerical Air License",50000],
   ["Pistollicense",gundealer1,"Pistol license",35000],
   ["riflelicense",vending2,"Hunting License",5000],
   ["assassinlic",assassinshop,"Illegal Assassin Weapons Fee",50000],
   ["terror",terrorbox,"Illegal Terrorist License",900000],
   ["probator",copbasic2,localize "STRS_license_probator",2000],
   ["patrol_training",copbank,localize "STRS_license_coppatrol",2500],
   ["sobr_training",copswat,localize "STRS_license_copswat",250000],
   ["cg_boat",copbank,"PD Patrol Boat Training",1000],
   ["Donator_licence",donatebuy1,"Donator License",100000],
   ["air_support_training",copbank,localize "STRS_license_copairsupport",5000]
];

INV_LizenzOwner = [];